### ISSUE TITLE
"Next Screen" script?

### ISSUE THREAD

**Issue by DarkNachtara** [zegreatclan/SimHub#286]
Hi,
I try to make an System Dashboard for my Pc and i run into a problem doing it.
I want to Have an Extra Screen for displaying my HHDs Storage but I didnt find something to access the screen i generated in the Dashboard

How can i switch between the Screens via ToggleButton??

**Comment by zegreatclan** [comment]
On the button you can use the following action : 

![image](https://user-images.githubusercontent.com/2207331/47387667-5462a680-d710-11e8-9dd9-da3f058eb3e4.png)

Also make sure that your secondary screen is configured as "idle" (and or ingame) otherwise simhub will refuse to switch to the screen if the current mode does not matches.

![image](https://user-images.githubusercontent.com/2207331/47387767-97247e80-d710-11e8-86b4-a767cf1aa4c4.png)

**Comment by DarkNachtara** [comment]
and now how can i display the hdd Storeage left for each HDD??

**Comment by zegreatclan** [comment]
You will find properties for each drive ,

To show them in a text you simply have to use bindings : https://github.com/zegreatclan/SimHub/wiki/Dash-Studio---Bindings
![image](https://user-images.githubusercontent.com/2207331/47389515-3fd4dd00-d715-11e8-9779-f7e68c102a24.png)
