### ISSUE TITLE
LCD 1602 2x16 blue - assetto corsa simhub

### ISSUE THREAD

**Issue by EBEALIEN** [zegreatclan/SimHub#310]
Good morning and happy New Year!

They gave me arduino starter kits, and I'm passionate about "Assetto Corsa". I tried to connect matrix 7219 with "simhub" and everything is fine. Now i would like to try the 1602 2x16 lcd module with the "arduino one" board,
but I can not find how to connect it and not even the sketch to interface it to race set-up. could she help me?

Thanks a lot of professor.
Antonio - EBEALIEN - ITALY - google translate

**Comment by zegreatclan** [comment]
Hi ! you will find all the required informations on the wiki : https://github.com/zegreatclan/SimHub/wiki/Arduino-20x4-or-16x2-I2C-LCD

**Comment by EBEALIEN** [comment]
> 
> 
> Hi ! you will find all the required informations on the wiki : https://github.com/zegreatclan/SimHub/wiki/Arduino-20x4-or-16x2-I2C-LCD

Thank you very much for your kindness,
I try this evening and then I report situation.

**Comment by zegreatclan** [comment]
Hi ! 
You have the full index of documentations here : 
https://github.com/zegreatclan/SimHub/wiki#arduino-support
I'm affraid it's impossible to produce documentation for every specific combinations users may want, but most of these modules are plug and  play, just assign pins in the setup tool, then you just have to wire the gnd and 5v separately to the arduino board (as it's not shown in the setup tool) . 

Take care the i2c lcd is one of the slowest device (due to i2c) and can't go above 7fps approximately  and mixing it with a tm1638 it will be really sensible. Combined with matrix it won't be so visible as gear only changes from time to time.

**Comment by EBEALIEN** [comment]
Hello,
I'm happy, very simple.
I have only connected matrix7219 and the tm1638 (the one with only the red leds). The program has done everything by itself with the utmost precision. **Fantastic.** The only problem is that the leds of the tm1638, they do not light up until the end,  but anyway I have not touched any configuration.
**A)** Tell me how to make another donation, it's the least!
**B)** if you want to change the title of the topic as there are info for more.
**C)** Thank you

**Comment by EBEALIEN** [comment]
For the donation -- Solved -- good!

**Comment by zegreatclan** [comment]
Perfect ;) Have fun !
