### ISSUE TITLE
CS:GO support

### ISSUE THREAD

**Issue by Tigrejor** [zegreatclan/SimHub#323]
Is there any guide regarding CS:GO support and how to setup some kind of dashboard with game's data? I couldn't seem to find any. Thanks in advance

**Comment by zegreatclan** [comment]
Hi ! 

I've made you a quick example : https://www.dropbox.com/s/o6yp1xsaxlxhytr/CSGO.simhubdash?dl=0

since cs:go is not a racing game most data are available in the "raw data" :
![image](https://user-images.githubusercontent.com/2207331/52535704-02db3780-2d52-11e9-8a7e-87ee9bb1abdd.png)

Then to give life to a dashboard you have to use bindings : https://github.com/zegreatclan/SimHub/wiki/Dash-Studio---Bindings
