### ISSUE TITLE
Arduino Micro Nextion Screen Problems

### ISSUE THREAD

**Issue by hoogin89** [zegreatclan/SimHub#325]
I'm coming to you guys today because I am beyond frustrated.  I have an Arduino Pro Micro Wired to a Nextion 4.3" display.  The Micro has its TX lead going to the Rx on the screen and the RX lead going to the TX on the screen.  I have tried to power it with an external power supply and the Micro as well.  Also the screen is indeed an NX screen not a Chinese knock off.  Here is my problem:

The screen will not talk to the micro at all.

-Loaded micro with all supported files supplied by simhub.  Origionally thought the Arduino setup would take care of this, (if it does please let me know) but decided that was maybe where my problem was so manually did it as well.  Still nothing.

-Verified all connections are strong to pins with a volt meter.  All are fine with little to no resistance.

-Re-did wiring because I heard the ground HAD to be connected to the micro for it to work.  Nothing.

-Checked micro for functionality, it runs a 3x3 matrix of buttons and 16 leds through sim hub flawlessly.

-Checked screen functionality, downloaded the dash with a usb ttl.  Downloaded just fine and worked.

Soooooo, why won't my Arduino talk to it?  What am I doing wrong.  Ive read the instructions a bajillion times and I just want to know where I'm wrong.  I'm extremely frustrated and to those who say that why don't i just use the ttl? well, it is an extra cable an extra port and I just want my whole system wrapped into one Arduino because of space and needing another coil cable.  I believe unless I'm stupid that I should be able to upload new dashs to the nextion from a micro and then that micro should be able to talk to it to display game data correct?  So what am I doing wrong?

Thank you all for your time.  I'm looking forward to your replies.

**Comment by zegreatclan** [comment]
Hi !

Indeed the sketch requires to operate nextion through the micro is not the same as the main arduino sketch (using setup tool)

I feel you have uploaded the wrong sketch, in order to operate with the screen it requires a  dedicated sketch, it's located here C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge.
It will offer nextion connnectivity, leds support and a "skeleton" for gamepad mode
(https://github.com/zegreatclan/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch)

Could you make sure to upload this particular sketch ? When uploaded the arduino micro will act as an USB TTL. 

When done make sure to use the specific process to upload templates,  : https://github.com/zegreatclan/SimHub/wiki/Nextion-Display#uploading-nextion-template-through-arduino-micro

Nicolas

**Comment by zegreatclan** [comment]
Solved right now on discord : for the records it was the wrong sketch.
Have fun !
