### ISSUE TITLE
New game support: F1 2019 and Moto GP 2019

### ISSUE THREAD

**Issue by camerusa** [zegreatclan/SimHub#359]
Hi could you please confirm if and how I can add F1 2019 and Moto GP 2019? Or should I wait for you to add those games with an new update?

Thank you

**Comment by zegreatclan** [comment]
Hi ! Concerning F12019 it's planned obviously, it  is ready based on the specifications published on the forum and I wait for the public early access to test it (June 25th), about MotoGP 19, sadly no telemetry available on this one (even if it was available on the 18 edition), if they add it I will be happy to support it

**Comment by camerusa** [comment]
> 
> 
> Hi ! Concerning F12019 it's planned obviously, it is ready based on the specifications published on the forum and I wait for the public early access to test it (June 25th), about MotoGP 19, sadly no telemetry available on this one (even if it was available on the 18 edition), if they add it I will be happy to support it

Thank you! So reactive! WOW! Keep up the great work.
While I have your attention do you know if ACC telemetry is responsible for showing best time 32.24.xx at the beginning of any session until you establish a time?

**Comment by zegreatclan** [comment]
Yes indeed, clearly the acc telemetry is not finished, I hope the will take some times to enhance it because it's really frustrating, data used to be empty in previous early access, it's now filled with bad data which is even worse. To be totally transparent I'm hesitant between cutting those data (and do another release when the game will be ready) or leave it like this hoping they will fix the data very soon. Currently acc have a good support of physical data (wheel slip, suspensions ...) But nothing is correct about session and indicators data (lap time ....)

**Comment by zegreatclan** [comment]
F12019 release is coming ;)

**Comment by camerusa** [comment]
Excellent! Thank you

**Comment by camerusa** [comment]
I just saw the new version on your official website! Download in progress
