### ISSUE TITLE
2x 2004lcd via i2c

### ISSUE THREAD

**Issue by KarlSteeg** [zegreatclan/SimHub#381]
hey all.

this may sound silly, but the support on racedepartment is no longer.
so hope you lads can assist.

My friend wants me to build him a dash.
using 2x 2004LCD side by side over I2C(planning 2 different address : x27, x3f)
one RPM counter using X27.589 dash stepper(aftermarket ones dont fit he's rig)
3x buttons to control pages on LCD
and one bi color LED for counter arm(iluminate blue for 0-redline,, red for red limiter)

any one know of any limitations in these components working together??
and how do i setup 2x LCD? seen pictures of it done, but no idea how to wire it up.

advice please?
Karl

**Comment by zegreatclan** [comment]
Hi ! 
Currently simhub supports only one 2004 per arduino. Supporting more would be too slow , with one you can expect 7fps (due to hardware capacity) with two ... well 3.5fps max, that would be definitely too slow (But it's possible to use two arduinos since simhub will drive them in parallel.)
For buttons yes it's supported : https://github.com/zegreatclan/SimHub/wiki/Arduino-Press-Buttons
About x27 or dual colour leds, i'm afraid none of them are supported : . It's possible to use the custom hardware support but this won't use any of the simhub integrated configuration UI ; https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support

NB : Not supporting simple leds (dual color, RGB or any leds without a proper integrated power driver) is an assumed decision from me, because arduino is not built to do this (you can see chapter #10 here : https://www.rugged-circuits.com/10-ways-to-destroy-an-arduino/ )

**Comment by KarlSteeg** [comment]
awesome.

many thanks for the reply,
2 nanos it is then.
thinking w2812b for the dial then.

why does x27 not work?   i have read that its readly controlled by arduino
size of x27 makes it perfect aswell as aftermarket having horrible distractions like flashing lights and huge bulky  frame

**Comment by KarlSteeg** [comment]
Hi 

ok, fair point with the LEDs, read your link and see how many can accidentally damage the arduino.
i have transistors to run LEDs from another project, i dont mind making a cute little PCB with the transistors and such on to drive the LEDs,  i just need to know how to assign 2 pins and get SimHub to high and low them based on rpm status.
it is going to be incredibly difficult for me to squeeze a w2812b led in a moving dial.


still not finding an alternative to the x27, RPM stepper

**Comment by zegreatclan** [comment]
Hi ! Sorry about the late reply, end of the holidays have been really busy, and catching up in progress stuffs not really easy :D 
About x27 I already have a feature request in progress https://github.com/zegreatclan/SimHub/issues/299
I can't say when it will be added for now
In the wait the costum protocol allows to add them, but it's not native indeed and will require a bit of code 

Wotever
